alter function data_commons.chado_dbxref_id_to_dbxref(bigint) owner to ermrest;
alter function data_commons.create_relationship_paths(bigint, bigint) owner to ermrest;
alter function data_commons.cvterm_add() owner to ermrest;
alter function data_commons.cvterm_generate_dbxref() owner to ermrest;
alter function data_commons.cvtermpath_add() owner to ermrest;
alter function data_commons.cvtermprop_add() owner to ermrest;
alter function data_commons.dbxref_set_name() owner to ermrest;
alter function data_commons.deregister_domain_table(name, name) owner to ermrest;
alter function data_commons.generate_dbxref(text) owner to ermrest;
alter function data_commons.make_domain_tables(name, name) owner to ermrest;
alter function data_commons.make_domain_tables(name, name, name, name) owner to ermrest;
alter function data_commons.populate_domain_cvterm() owner to ermrest;
alter function data_commons.populate_domain_tables_from_cvterm() owner to ermrest;
alter function data_commons.push_cvterm_updates() owner to ermrest;
alter function data_commons.push_path_table_entries(name, name, name, name, name, name, text) owner to ermrest;
alter function data_commons.register_domain_table(name, name, name, name, name, name) owner to ermrest;
alter function data_commons.relationship_set_cv() owner to ermrest;
alter function data_commons.update_dbxref_array() owner to ermrest;
alter function data_commons.update_domain_paths_from_relationship_type() owner to ermrest;
alter function data_commons.update_relationshiptype_properties() owner to ermrest;
alter function data_commons.update_synonym_array() owner to ermrest;
